using PCBAssemblyConverter.Presentation.Web.Mime.Attributes;

namespace PCBAssemblyConverter.Presentation.Web.Mime.Definitions
{
    public enum AudioSubtype
    {
        //[MediaTypeName("1d-interleaved-parityfec")]
        //_1dInterleavedParityfec,
        //[MediaTypeName("32kadpcm")]
        //_32kadpcm,
        //[MediaTypeName("3gpp")]
        //_3gpp,
        //[MediaTypeName("3gpp2")]
        //_3gpp2,
        //[MediaTypeName("aac")]
        //Aac,
        //[MediaTypeName("ac3")]
        //Ac3,
        //[MediaTypeName("AMR")]
        //AMR,
        //[MediaTypeName("AMR-WB")]
        //AMRWB,
        //[MediaTypeName("amr-wb+")]
        //AmrWb_plus_,
        //[MediaTypeName("aptx")]
        //Aptx,
        //[MediaTypeName("asc")]
        //Asc,
        //[MediaTypeName("ATRAC-ADVANCED-LOSSLESS")]
        //ATRACADVANCEDLOSSLESS,
        //[MediaTypeName("ATRAC-X")]
        //ATRACX,
        //[MediaTypeName("ATRAC3")]
        //ATRAC3,
        //[MediaTypeName("basic")]
        //Basic,
        //[MediaTypeName("BV16")]
        //BV16,
        //[MediaTypeName("BV32")]
        //BV32,
        //[MediaTypeName("clearmode")]
        //Clearmode,
        //[MediaTypeName("CN")]
        //CN,
        //[MediaTypeName("DAT12")]
        //DAT12,
        //[MediaTypeName("dls")]
        //Dls,
        //[MediaTypeName("dsr-es201108")]
        //DsrEs201108,
        //[MediaTypeName("dsr-es202050")]
        //DsrEs202050,
        //[MediaTypeName("dsr-es202211")]
        //DsrEs202211,
        //[MediaTypeName("dsr-es202212")]
        //DsrEs202212,
        //[MediaTypeName("DV")]
        //DV,
        //[MediaTypeName("DVI4")]
        //DVI4,
        //[MediaTypeName("eac3")]
        //Eac3,
        //[MediaTypeName("encaprtp")]
        //Encaprtp,
        //[MediaTypeName("EVRC")]
        //EVRC,
        //[MediaTypeName("EVRC-QCP")]
        //EVRCQCP,
        //[MediaTypeName("EVRC0")]
        //EVRC0,
        //[MediaTypeName("EVRC1")]
        //EVRC1,
        //[MediaTypeName("EVRCB")]
        //EVRCB,
        //[MediaTypeName("EVRCB0")]
        //EVRCB0,
        //[MediaTypeName("EVRCB1")]
        //EVRCB1,
        //[MediaTypeName("EVRCNW")]
        //EVRCNW,
        //[MediaTypeName("EVRCNW0")]
        //EVRCNW0,
        //[MediaTypeName("EVRCNW1")]
        //EVRCNW1,
        //[MediaTypeName("EVRCWB")]
        //EVRCWB,
        //[MediaTypeName("EVRCWB0")]
        //EVRCWB0,
        //[MediaTypeName("EVRCWB1")]
        //EVRCWB1,
        //[MediaTypeName("EVS")]
        //EVS,
        //[MediaTypeName("example")]
        //Example,
        //[MediaTypeName("flac")]
        //Flac,
        //[MediaTypeName("flexfec")]
        //Flexfec,
        //[MediaTypeName("fwdred")]
        //Fwdred,
        //[MediaTypeName("G711-0")]
        //G7110,
        //[MediaTypeName("G719")]
        //G719,
        //[MediaTypeName("G7221")]
        //G7221,
        //[MediaTypeName("G722")]
        //G722,
        //[MediaTypeName("G723")]
        //G723,
        //[MediaTypeName("G726-16")]
        //G72616,
        //[MediaTypeName("G726-24")]
        //G72624,
        //[MediaTypeName("G726-32")]
        //G72632,
        //[MediaTypeName("G726-40")]
        //G72640,
        //[MediaTypeName("G728")]
        //G728,
        //[MediaTypeName("G729")]
        //G729,
        //[MediaTypeName("G7291")]
        //G7291,
        //[MediaTypeName("G729D")]
        //G729D,
        //[MediaTypeName("G729E")]
        //G729E,
        //[MediaTypeName("GSM")]
        //GSM,
        //[MediaTypeName("GSM-EFR")]
        //GSMEFR,
        //[MediaTypeName("GSM-HR-08")]
        //GSMHR08,
        //[MediaTypeName("iLBC")]
        //ILBC,
        //[MediaTypeName("ip-mr_v2.5")]
        //IpMr_V25,
        //[MediaTypeName("L8")]
        //L8,
        //[MediaTypeName("L16")]
        //L16,
        //[MediaTypeName("L20")]
        //L20,
        //[MediaTypeName("L24")]
        //L24,
        //[MediaTypeName("LPC")]
        //LPC,
        //[MediaTypeName("matroska")]
        //Matroska,
        //[MediaTypeName("MELP")]
        //MELP,
        //[MediaTypeName("MELP600")]
        //MELP600,
        //[MediaTypeName("MELP1200")]
        //MELP1200,
        //[MediaTypeName("MELP2400")]
        //MELP2400,
        //[MediaTypeName("mhas")]
        //Mhas,
        //[MediaTypeName("midi-clip")]
        //MidiClip,
        //[MediaTypeName("mobile-xmf")]
        //MobileXmf,
        //[MediaTypeName("MPA")]
        //MPA,
        //[MediaTypeName("mp4")]
        //Mp4,
        //[MediaTypeName("MP4A-LATM")]
        //MP4ALATM,
        //[MediaTypeName("mpa-robust")]
        //MpaRobust,
        //[MediaTypeName("mpeg")]
        //Mpeg,
        //[MediaTypeName("mpeg4-generic")]
        //Mpeg4Generic,
        //[MediaTypeName("ogg")]
        //Ogg,
        //[MediaTypeName("opus")]
        //Opus,
        //[MediaTypeName("parityfec")]
        //Parityfec,
        //[MediaTypeName("PCMA")]
        //PCMA,
        //[MediaTypeName("PCMA-WB")]
        //PCMAWB,
        //[MediaTypeName("PCMU")]
        //PCMU,
        //[MediaTypeName("PCMU-WB")]
        //PCMUWB,
        //[MediaTypeName("prs.sid")]
        //PrsSid,
        //[MediaTypeName("QCELP")]
        //QCELP,
        //[MediaTypeName("raptorfec")]
        //Raptorfec,
        //[MediaTypeName("RED")]
        //RED,
        //[MediaTypeName("rtp-enc-aescm128")]
        //RtpEncAescm128,
        //[MediaTypeName("rtploopback")]
        //Rtploopback,
        //[MediaTypeName("rtp-midi")]
        //RtpMidi,
        //[MediaTypeName("rtx")]
        //Rtx,
        //[MediaTypeName("scip")]
        //Scip,
        //[MediaTypeName("SMV")]
        //SMV,
        //[MediaTypeName("SMV0")]
        //SMV0,
        //[MediaTypeName("SMV-QCP")]
        //SMVQCP,
        //[MediaTypeName("sofa")]
        //Sofa,
        //[MediaTypeName("soundfont")]
        //Soundfont,
        //[MediaTypeName("sp-midi")]
        //SpMidi,
        //[MediaTypeName("speex")]
        //Speex,
        //[MediaTypeName("t140c")]
        //T140c,
        //[MediaTypeName("t38")]
        //T38,
        //[MediaTypeName("telephone-event")]
        //TelephoneEvent,
        //[MediaTypeName("TETRA_ACELP")]
        //TETRA_ACELP,
        //[MediaTypeName("TETRA_ACELP_BB")]
        //TETRA_ACELP_BB,
        //[MediaTypeName("tone")]
        //Tone,
        //[MediaTypeName("TSVCIS")]
        //TSVCIS,
        //[MediaTypeName("UEMCLIP")]
        //UEMCLIP,
        //[MediaTypeName("ulpfec")]
        //Ulpfec,
        //[MediaTypeName("usac")]
        //Usac,
        //[MediaTypeName("VDVI")]
        //VDVI,
        //[MediaTypeName("VMR-WB")]
        //VMRWB,
        //[MediaTypeName("vnd.3gpp.iufp")]
        //Vnd3gppIufp,
        //[MediaTypeName("vnd.4SB")]
        //Vnd4SB,
        //[MediaTypeName("vnd.audiokoz")]
        //VndAudiokoz,
        //[MediaTypeName("vnd.blockfact.facta")]
        //VndBlockfactFacta,
        //[MediaTypeName("vnd.CELP")]
        //VndCELP,
        //[MediaTypeName("vnd.cisco.nse")]
        //VndCiscoNse,
        //[MediaTypeName("vnd.cmles.radio-events")]
        //VndCmlesRadioEvents,
        //[MediaTypeName("vnd.cns.anp1")]
        //VndCnsAnp1,
        //[MediaTypeName("vnd.cns.inf1")]
        //VndCnsInf1,
        //[MediaTypeName("vnd.dece.audio")]
        //VndDeceAudio,
        //[MediaTypeName("vnd.digital-winds")]
        //VndDigitalWinds,
        //[MediaTypeName("vnd.dlna.adts")]
        //VndDlnaAdts,
        //[MediaTypeName("vnd.dolby.heaac.1")]
        //VndDolbyHeaac1,
        //[MediaTypeName("vnd.dolby.heaac.2")]
        //VndDolbyHeaac2,
        //[MediaTypeName("vnd.dolby.mlp")]
        //VndDolbyMlp,
        //[MediaTypeName("vnd.dolby.mps")]
        //VndDolbyMps,
        //[MediaTypeName("vnd.dolby.pl2")]
        //VndDolbyPl2,
        //[MediaTypeName("vnd.dolby.pl2x")]
        //VndDolbyPl2x,
        //[MediaTypeName("vnd.dolby.pl2z")]
        //VndDolbyPl2z,
        //[MediaTypeName("vnd.dolby.pulse.1")]
        //VndDolbyPulse1,
        //[MediaTypeName("vnd.dra")]
        //VndDra,
        //[MediaTypeName("vnd.dts")]
        //VndDts,
        //[MediaTypeName("vnd.dts.hd")]
        //VndDtsHd,
        //[MediaTypeName("vnd.dts.uhd")]
        //VndDtsUhd,
        //[MediaTypeName("vnd.dvb.file")]
        //VndDvbFile,
        //[MediaTypeName("vnd.everad.plj")]
        //VndEveradPlj,
        //[MediaTypeName("vnd.hns.audio")]
        //VndHnsAudio,
        //[MediaTypeName("vnd.lucent.voice")]
        //VndLucentVoice,
        //[MediaTypeName("vnd.ms-playready.media.pya")]
        //VndMsPlayreadyMediaPya,
        //[MediaTypeName("vnd.nokia.mobile-xmf")]
        //VndNokiaMobileXmf,
        //[MediaTypeName("vnd.nortel.vbk")]
        //VndNortelVbk,
        //[MediaTypeName("vnd.nuera.ecelp4800")]
        //VndNueraEcelp4800,
        //[MediaTypeName("vnd.nuera.ecelp7470")]
        //VndNueraEcelp7470,
        //[MediaTypeName("vnd.nuera.ecelp9600")]
        //VndNueraEcelp9600,
        //[MediaTypeName("vnd.octel.sbc")]
        //VndOctelSbc,
        //[MediaTypeName("vnd.presonus.multitrack")]
        //VndPresonusMultitrack,
        //[MediaTypeName("vnd.qcelp")]
        //VndQcelp,
        //[MediaTypeName("vnd.rhetorex.32kadpcm")]
        //VndRhetorex32kadpcm,
        //[MediaTypeName("vnd.rip")]
        //VndRip,
        //[MediaTypeName("vnd.sealedmedia.softseal.mpeg")]
        //VndSealedmediaSoftsealMpeg,
        //[MediaTypeName("vnd.vmx.cvsd")]
        //VndVmxCvsd,
        //[MediaTypeName("vorbis")]
        //Vorbis,
        //[MediaTypeName("vorbis-config")]
        //VorbisConfig,
    }
}
