using PCBAssemblyConverter.Presentation.Web.Mime.Attributes;

namespace PCBAssemblyConverter.Presentation.Web.Mime.Definitions
{
    public enum ImageSubtype
    {
        //[MediaTypeName("aces")]
        //Aces,
        //[MediaTypeName("apng")]
        //Apng,
        //[MediaTypeName("avci")]
        //Avci,
        //[MediaTypeName("avcs")]
        //Avcs,
        //[MediaTypeName("avif")]
        //Avif,
        //[MediaTypeName("bmp")]
        //Bmp,
        //[MediaTypeName("cgm")]
        //Cgm,
        //[MediaTypeName("dicom-rle")]
        //DicomRle,
        //[MediaTypeName("dpx")]
        //Dpx,
        //[MediaTypeName("emf")]
        //Emf,
        //[MediaTypeName("example")]
        //Example,
        //[MediaTypeName("fits")]
        //Fits,
        //[MediaTypeName("g3fax")]
        //G3fax,
        //[MediaTypeName("gif")]
        //Gif,
        //[MediaTypeName("heic")]
        //Heic,
        //[MediaTypeName("heic-sequence")]
        //HeicSequence,
        //[MediaTypeName("heif")]
        //Heif,
        //[MediaTypeName("heif-sequence")]
        //HeifSequence,
        //[MediaTypeName("hej2k")]
        //Hej2k,
        //[MediaTypeName("hsj2")]
        //Hsj2,
        //[MediaTypeName("ief")]
        //Ief,
        //[MediaTypeName("j2c")]
        //J2c,
        //[MediaTypeName("jaii")]
        //Jaii,
        //[MediaTypeName("jais")]
        //Jais,
        //[MediaTypeName("jls")]
        //Jls,
        //[MediaTypeName("jp2")]
        //Jp2,
        //[MediaTypeName("jpeg")]
        //Jpeg,
        //[MediaTypeName("jph")]
        //Jph,
        //[MediaTypeName("jphc")]
        //Jphc,
        //[MediaTypeName("jpm")]
        //Jpm,
        //[MediaTypeName("jpx")]
        //Jpx,
        //[MediaTypeName("jxl")]
        //Jxl,
        //[MediaTypeName("jxr")]
        //Jxr,
        //[MediaTypeName("jxrA")]
        //JxrA,
        //[MediaTypeName("jxrS")]
        //JxrS,
        //[MediaTypeName("jxs")]
        //Jxs,
        //[MediaTypeName("jxsc")]
        //Jxsc,
        //[MediaTypeName("jxsi")]
        //Jxsi,
        //[MediaTypeName("jxss")]
        //Jxss,
        //[MediaTypeName("ktx")]
        //Ktx,
        //[MediaTypeName("ktx2")]
        //Ktx2,
        //[MediaTypeName("naplps")]
        //Naplps,
        //[MediaTypeName("png")]
        //Png,
        //[MediaTypeName("prs.btif")]
        //PrsBtif,
        //[MediaTypeName("prs.pti")]
        //PrsPti,
        //[MediaTypeName("pwg-raster")]
        //PwgRaster,
        //[MediaTypeName("svg+xml")]
        //Svg_plus_Xml,
        //[MediaTypeName("t38")]
        //T38,
        //[MediaTypeName("tiff")]
        //Tiff,
        //[MediaTypeName("tiff-fx")]
        //TiffFx,
        //[MediaTypeName("vnd.adobe.photoshop")]
        //VndAdobePhotoshop,
        //[MediaTypeName("vnd.airzip.accelerator.azv")]
        //VndAirzipAcceleratorAzv,
        //[MediaTypeName("vnd.blockfact.facti")]
        //VndBlockfactFacti,
        //[MediaTypeName("vnd.clip")]
        //VndClip,
        //[MediaTypeName("vnd.cns.inf2")]
        //VndCnsInf2,
        //[MediaTypeName("vnd.dece.graphic")]
        //VndDeceGraphic,
        //[MediaTypeName("vnd.djvu")]
        //VndDjvu,
        //[MediaTypeName("vnd.dwg")]
        //VndDwg,
        //[MediaTypeName("vnd.dxf")]
        //VndDxf,
        //[MediaTypeName("vnd.dvb.subtitle")]
        //VndDvbSubtitle,
        //[MediaTypeName("vnd.fastbidsheet")]
        //VndFastbidsheet,
        //[MediaTypeName("vnd.fpx")]
        //VndFpx,
        //[MediaTypeName("vnd.fst")]
        //VndFst,
        //[MediaTypeName("vnd.fujixerox.edmics-mmr")]
        //VndFujixeroxEdmicsMmr,
        //[MediaTypeName("vnd.fujixerox.edmics-rlc")]
        //VndFujixeroxEdmicsRlc,
        //[MediaTypeName("vnd.globalgraphics.pgb")]
        //VndGlobalgraphicsPgb,
        //[MediaTypeName("vnd.microsoft.icon")]
        //VndMicrosoftIcon,
        //[MediaTypeName("vnd.mix")]
        //VndMix,
        //[MediaTypeName("vnd.ms-modi")]
        //VndMsModi,
        //[MediaTypeName("vnd.mozilla.apng")]
        //VndMozillaApng,
        //[MediaTypeName("vnd.net-fpx")]
        //VndNetFpx,
        //[MediaTypeName("vnd.pco.b16")]
        //VndPcoB16,
        //[MediaTypeName("vnd.radiance")]
        //VndRadiance,
        //[MediaTypeName("vnd.sealed.png")]
        //VndSealedPng,
        //[MediaTypeName("vnd.sealedmedia.softseal.gif")]
        //VndSealedmediaSoftsealGif,
        //[MediaTypeName("vnd.sld")]
        //VndSld,
        //[MediaTypeName("vnd.sealedmedia.softseal.jpg")]
        //VndSealedmediaSoftsealJpg,
        //[MediaTypeName("vnd.svf")]
        //VndSvf,
        //[MediaTypeName("vnd.tencent.tap")]
        //VndTencentTap,
        //[MediaTypeName("vnd.valve.source.texture")]
        //VndValveSourceTexture,
        //[MediaTypeName("vnd.wap.wbmp")]
        //VndWapWbmp,
        //[MediaTypeName("vnd.xiff")]
        //VndXiff,
        //[MediaTypeName("vnd.zbrush.pcx")]
        //VndZbrushPcx,
        //[MediaTypeName("webp")]
        //Webp,
        //[MediaTypeName("wmf")]
        //Wmf,
        //[MediaTypeName("x-emf")]
        //XEmf,
        //[MediaTypeName("x-wmf")]
        //XWmf,
    }
}
