using PCBAssemblyConverter.Presentation.Web.Mime.Attributes;

namespace PCBAssemblyConverter.Presentation.Web.Mime.Definitions
{
    public enum ModelSubtype
    {
        //[MediaTypeName("3mf")]
        //_3mf,
        //[MediaTypeName("e57")]
        //E57,
        //[MediaTypeName("example")]
        //Example,
        //[MediaTypeName("gltf-binary")]
        //GltfBinary,
        //[MediaTypeName("gltf+json")]
        //Gltf_plus_Json,
        //[MediaTypeName("JT")]
        //JT,
        //[MediaTypeName("iges")]
        //Iges,
        //[MediaTypeName("mesh")]
        //Mesh,
        //[MediaTypeName("mtl")]
        //Mtl,
        //[MediaTypeName("obj")]
        //Obj,
        //[MediaTypeName("prc")]
        //Prc,
        //[MediaTypeName("step")]
        //Step,
        //[MediaTypeName("step+xml")]
        //Step_plus_Xml,
        //[MediaTypeName("step+zip")]
        //Step_plus_Zip,
        //[MediaTypeName("step-xml+zip")]
        //StepXml_plus_Zip,
        //[MediaTypeName("stl")]
        //Stl,
        //[MediaTypeName("u3d")]
        //U3d,
        //[MediaTypeName("vnd.bary")]
        //VndBary,
        //[MediaTypeName("vnd.cld")]
        //VndCld,
        //[MediaTypeName("vnd.collada+xml")]
        //VndCollada_plus_Xml,
        //[MediaTypeName("vnd.dwf")]
        //VndDwf,
        //[MediaTypeName("vnd.flatland.3dml")]
        //VndFlatland3dml,
        //[MediaTypeName("vnd.gdl")]
        //VndGdl,
        //[MediaTypeName("vnd.gs-gdl")]
        //VndGsGdl,
        //[MediaTypeName("vnd.gtw")]
        //VndGtw,
        //[MediaTypeName("vnd.moml+xml")]
        //VndMoml_plus_Xml,
        //[MediaTypeName("vnd.mts")]
        //VndMts,
        //[MediaTypeName("vnd.opengex")]
        //VndOpengex,
        //[MediaTypeName("vnd.parasolid.transmit.binary")]
        //VndParasolidTransmitBinary,
        //[MediaTypeName("vnd.parasolid.transmit.text")]
        //VndParasolidTransmitText,
        //[MediaTypeName("vnd.pytha.pyox")]
        //VndPythaPyox,
        //[MediaTypeName("vnd.rosette.annotated-data-model")]
        //VndRosetteAnnotatedDataModel,
        //[MediaTypeName("vnd.sap.vds")]
        //VndSapVds,
        //[MediaTypeName("vnd.usda")]
        //VndUsda,
        //[MediaTypeName("vnd.usdz+zip")]
        //VndUsdz_plus_Zip,
        //[MediaTypeName("vnd.valve.source.compiled-map")]
        //VndValveSourceCompiledMap,
        //[MediaTypeName("vnd.vtu")]
        //VndVtu,
        //[MediaTypeName("vrml")]
        //Vrml,
        //[MediaTypeName("x3d-vrml")]
        //X3dVrml,
        //[MediaTypeName("x3d+fastinfoset")]
        //X3d_plus_Fastinfoset,
        //[MediaTypeName("x3d+xml")]
        //X3d_plus_Xml,
    }
}
