using PCBAssemblyConverter.Presentation.Web.Mime.Attributes;

namespace PCBAssemblyConverter.Presentation.Web.Mime.Definitions
{
    public enum TextSubtype
    {
        //[MediaTypeName("1d-interleaved-parityfec")]
        //_1dInterleavedParityfec,
        //[MediaTypeName("cache-manifest")]
        //CacheManifest,
        //[MediaTypeName("calendar")]
        //Calendar,
        //[MediaTypeName("cql")]
        //Cql,
        //[MediaTypeName("cql-expression")]
        //CqlExpression,
        //[MediaTypeName("cql-identifier")]
        //CqlIdentifier,
        //[MediaTypeName("css")]
        //Css,
        [MediaTypeName("csv")]
        [MediaTypeExtension(".csv")]
        Csv,
        //[MediaTypeName("csv-schema")]
        //CsvSchema,
        //[MediaTypeName("directory")]
        //Directory,
        //[MediaTypeName("dns")]
        //Dns,
        //[MediaTypeName("ecmascript")]
        //Ecmascript,
        //[MediaTypeName("encaprtp")]
        //Encaprtp,
        //[MediaTypeName("enriched")]
        //Enriched,
        //[MediaTypeName("example")]
        //Example,
        //[MediaTypeName("fhirpath")]
        //Fhirpath,
        //[MediaTypeName("flexfec")]
        //Flexfec,
        //[MediaTypeName("fwdred")]
        //Fwdred,
        //[MediaTypeName("gff3")]
        //Gff3,
        //[MediaTypeName("grammar-ref-list")]
        //GrammarRefList,
        //[MediaTypeName("hl7v2")]
        //Hl7v2,
        //[MediaTypeName("html")]
        //Html,
        //[MediaTypeName("javascript")]
        //Javascript,
        //[MediaTypeName("jcr-cnd")]
        //JcrCnd,
        //[MediaTypeName("markdown")]
        //Markdown,
        //[MediaTypeName("mizar")]
        //Mizar,
        //[MediaTypeName("n3")]
        //N3,
        //[MediaTypeName("org")]
        //Org,
        //[MediaTypeName("parameters")]
        //Parameters,
        //[MediaTypeName("parityfec")]
        //Parityfec,
        [MediaTypeName("plain")]
        Plain,
        //[MediaTypeName("provenance-notation")]
        //ProvenanceNotation,
        //[MediaTypeName("prs.fallenstein.rst")]
        //PrsFallensteinRst,
        //[MediaTypeName("prs.lines.tag")]
        //PrsLinesTag,
        //[MediaTypeName("prs.prop.logic")]
        //PrsPropLogic,
        //[MediaTypeName("prs.texi")]
        //PrsTexi,
        //[MediaTypeName("raptorfec")]
        //Raptorfec,
        //[MediaTypeName("RED")]
        //RED,
        //[MediaTypeName("rfc822-headers")]
        //Rfc822Headers,
        //[MediaTypeName("richtext")]
        //Richtext,
        //[MediaTypeName("rtf")]
        //Rtf,
        //[MediaTypeName("rtp-enc-aescm128")]
        //RtpEncAescm128,
        //[MediaTypeName("rtploopback")]
        //Rtploopback,
        //[MediaTypeName("rtx")]
        //Rtx,
        //[MediaTypeName("SGML")]
        //SGML,
        //[MediaTypeName("shaclc")]
        //Shaclc,
        //[MediaTypeName("shex")]
        //Shex,
        //[MediaTypeName("spdx")]
        //Spdx,
        //[MediaTypeName("strings")]
        //Strings,
        //[MediaTypeName("t140")]
        //T140,
        //[MediaTypeName("tab-separated-values")]
        //TabSeparatedValues,
        //[MediaTypeName("troff")]
        //Troff,
        //[MediaTypeName("turtle")]
        //Turtle,
        //[MediaTypeName("ulpfec")]
        //Ulpfec,
        //[MediaTypeName("uri-list")]
        //UriList,
        //[MediaTypeName("vcard")]
        //Vcard,
        //[MediaTypeName("vnd.a")]
        //VndA,
        //[MediaTypeName("vnd.abc")]
        //VndAbc,
        //[MediaTypeName("vnd.ascii-art")]
        //VndAsciiArt,
        //[MediaTypeName("vnd.curl")]
        //VndCurl,
        //[MediaTypeName("vnd.debian.copyright")]
        //VndDebianCopyright,
        //[MediaTypeName("vnd.DMClientScript")]
        //VndDMClientScript,
        //[MediaTypeName("vnd.dvb.subtitle")]
        //VndDvbSubtitle,
        //[MediaTypeName("vnd.esmertec.theme-descriptor")]
        //VndEsmertecThemeDescriptor,
        //[MediaTypeName("vnd.exchangeable")]
        //VndExchangeable,
        //[MediaTypeName("vnd.familysearch.gedcom")]
        //VndFamilysearchGedcom,
        //[MediaTypeName("vnd.ficlab.flt")]
        //VndFiclabFlt,
        //[MediaTypeName("vnd.fly")]
        //VndFly,
        //[MediaTypeName("vnd.fmi.flexstor")]
        //VndFmiFlexstor,
        //[MediaTypeName("vnd.gml")]
        //VndGml,
        //[MediaTypeName("vnd.graphviz")]
        //VndGraphviz,
        //[MediaTypeName("vnd.hans")]
        //VndHans,
        //[MediaTypeName("vnd.hekaya")]
        //VndHekaya,
        //[MediaTypeName("vnd.hgl")]
        //VndHgl,
        //[MediaTypeName("vnd.in3d.3dml")]
        //VndIn3d3dml,
        //[MediaTypeName("vnd.in3d.spot")]
        //VndIn3dSpot,
        //[MediaTypeName("vnd.IPTC.NewsML")]
        //VndIPTCNewsML,
        //[MediaTypeName("vnd.IPTC.NITF")]
        //VndIPTCNITF,
        //[MediaTypeName("vnd.latex-z")]
        //VndLatexZ,
        //[MediaTypeName("vnd.longform")]
        //VndLongform,
        //[MediaTypeName("vnd.motorola.reflex")]
        //VndMotorolaReflex,
        //[MediaTypeName("vnd.ms-mediapackage")]
        //VndMsMediapackage,
        //[MediaTypeName("vnd.net2phone.commcenter.command")]
        //VndNet2phoneCommcenterCommand,
        //[MediaTypeName("vnd.radisys.msml-basic-layout")]
        //VndRadisysMsmlBasicLayout,
        //[MediaTypeName("vnd.senx.warpscript")]
        //VndSenxWarpscript,
        //[MediaTypeName("vnd.si.uricatalogue")]
        //VndSiUricatalogue,
        //[MediaTypeName("vnd.sun.j2me.app-descriptor")]
        //VndSunJ2meAppDescriptor,
        //[MediaTypeName("vnd.sosi")]
        //VndSosi,
        //[MediaTypeName("vnd.tps")]
        //VndTps,
        //[MediaTypeName("vnd.typst")]
        //VndTypst,
        //[MediaTypeName("vnd.trolltech.linguist")]
        //VndTrolltechLinguist,
        //[MediaTypeName("vnd.vcf")]
        //VndVcf,
        //[MediaTypeName("vnd.vri")]
        //VndVri,
        //[MediaTypeName("vnd.wap.si")]
        //VndWapSi,
        //[MediaTypeName("vnd.wap.sl")]
        //VndWapSl,
        //[MediaTypeName("vnd.wap.wml")]
        //VndWapWml,
        //[MediaTypeName("vnd.wap.wmlscript")]
        //VndWapWmlscript,
        //[MediaTypeName("vnd.zoo.kcl")]
        //VndZooKcl,
        //[MediaTypeName("vtt")]
        //Vtt,
        //[MediaTypeName("wgsl")]
        //Wgsl,
        //[MediaTypeName("xml")]
        //Xml,
        //[MediaTypeName("xml-external-parsed-entity")]
        //XmlExternalParsedEntity,
    }
}
