using PCBAssemblyConverter.Presentation.Web.Mime.Attributes;

namespace PCBAssemblyConverter.Presentation.Web.Mime.Definitions
{
    public enum VideoSubtype
    {
        //[MediaTypeName("1d-interleaved-parityfec")]
        //_1dInterleavedParityfec,
        //[MediaTypeName("3gpp")]
        //_3gpp,
        //[MediaTypeName("3gpp2")]
        //_3gpp2,
        //[MediaTypeName("3gpp-tt")]
        //_3gppTt,
        //[MediaTypeName("AV1")]
        //AV1,
        //[MediaTypeName("BMPEG")]
        //BMPEG,
        //[MediaTypeName("BT656")]
        //BT656,
        //[MediaTypeName("CelB")]
        //CelB,
        //[MediaTypeName("DV")]
        //DV,
        //[MediaTypeName("encaprtp")]
        //Encaprtp,
        //[MediaTypeName("evc")]
        //Evc,
        //[MediaTypeName("example")]
        //Example,
        //[MediaTypeName("FFV1")]
        //FFV1,
        //[MediaTypeName("flexfec")]
        //Flexfec,
        //[MediaTypeName("H261")]
        //H261,
        //[MediaTypeName("H263")]
        //H263,
        //[MediaTypeName("H263-1998")]
        //H2631998,
        //[MediaTypeName("H263-2000")]
        //H2632000,
        //[MediaTypeName("H264")]
        //H264,
        //[MediaTypeName("H264-RCDO")]
        //H264RCDO,
        //[MediaTypeName("H264-SVC")]
        //H264SVC,
        //[MediaTypeName("H265")]
        //H265,
        //[MediaTypeName("H266")]
        //H266,
        //[MediaTypeName("iso.segment")]
        //IsoSegment,
        //[MediaTypeName("JPEG")]
        //JPEG,
        //[MediaTypeName("jpeg2000")]
        //Jpeg2000,
        //[MediaTypeName("jpeg2000-scl")]
        //Jpeg2000Scl,
        //[MediaTypeName("jxsv")]
        //Jxsv,
        //[MediaTypeName("lottie+json")]
        //Lottie_plus_Json,
        //[MediaTypeName("matroska")]
        //Matroska,
        //[MediaTypeName("matroska-3d")]
        //Matroska3d,
        //[MediaTypeName("mj2")]
        //Mj2,
        //[MediaTypeName("MP1S")]
        //MP1S,
        //[MediaTypeName("MP2P")]
        //MP2P,
        //[MediaTypeName("MP2T")]
        //MP2T,
        //[MediaTypeName("mp4")]
        //Mp4,
        //[MediaTypeName("MP4V-ES")]
        //MP4VES,
        //[MediaTypeName("MPV")]
        //MPV,
        //[MediaTypeName("mpeg")]
        //Mpeg,
        //[MediaTypeName("mpeg4-generic")]
        //Mpeg4Generic,
        //[MediaTypeName("nv")]
        //Nv,
        //[MediaTypeName("ogg")]
        //Ogg,
        //[MediaTypeName("parityfec")]
        //Parityfec,
        //[MediaTypeName("pointer")]
        //Pointer,
        //[MediaTypeName("quicktime")]
        //Quicktime,
        //[MediaTypeName("raptorfec")]
        //Raptorfec,
        //[MediaTypeName("raw")]
        //Raw,
        //[MediaTypeName("rtp-enc-aescm128")]
        //RtpEncAescm128,
        //[MediaTypeName("rtploopback")]
        //Rtploopback,
        //[MediaTypeName("rtx")]
        //Rtx,
        //[MediaTypeName("scip")]
        //Scip,
        //[MediaTypeName("smpte291")]
        //Smpte291,
        //[MediaTypeName("SMPTE292M")]
        //SMPTE292M,
        //[MediaTypeName("ulpfec")]
        //Ulpfec,
        //[MediaTypeName("vc1")]
        //Vc1,
        //[MediaTypeName("vc2")]
        //Vc2,
        //[MediaTypeName("vnd.blockfact.factv")]
        //VndBlockfactFactv,
        //[MediaTypeName("vnd.CCTV")]
        //VndCCTV,
        //[MediaTypeName("vnd.dece.hd")]
        //VndDeceHd,
        //[MediaTypeName("vnd.dece.mobile")]
        //VndDeceMobile,
        //[MediaTypeName("vnd.dece.mp4")]
        //VndDeceMp4,
        //[MediaTypeName("vnd.dece.pd")]
        //VndDecePd,
        //[MediaTypeName("vnd.dece.sd")]
        //VndDeceSd,
        //[MediaTypeName("vnd.dece.video")]
        //VndDeceVideo,
        //[MediaTypeName("vnd.directv.mpeg")]
        //VndDirectvMpeg,
        //[MediaTypeName("vnd.directv.mpeg-tts")]
        //VndDirectvMpegTts,
        //[MediaTypeName("vnd.dlna.mpeg-tts")]
        //VndDlnaMpegTts,
        //[MediaTypeName("vnd.dvb.file")]
        //VndDvbFile,
        //[MediaTypeName("vnd.fvt")]
        //VndFvt,
        //[MediaTypeName("vnd.hns.video")]
        //VndHnsVideo,
        //[MediaTypeName("vnd.iptvforum.1dparityfec-1010")]
        //VndIptvforum1dparityfec1010,
        //[MediaTypeName("vnd.iptvforum.1dparityfec-2005")]
        //VndIptvforum1dparityfec2005,
        //[MediaTypeName("vnd.iptvforum.2dparityfec-1010")]
        //VndIptvforum2dparityfec1010,
        //[MediaTypeName("vnd.iptvforum.2dparityfec-2005")]
        //VndIptvforum2dparityfec2005,
        //[MediaTypeName("vnd.iptvforum.ttsavc")]
        //VndIptvforumTtsavc,
        //[MediaTypeName("vnd.iptvforum.ttsmpeg2")]
        //VndIptvforumTtsmpeg2,
        //[MediaTypeName("vnd.motorola.video")]
        //VndMotorolaVideo,
        //[MediaTypeName("vnd.motorola.videop")]
        //VndMotorolaVideop,
        //[MediaTypeName("vnd.mpegurl")]
        //VndMpegurl,
        //[MediaTypeName("vnd.ms-playready.media.pyv")]
        //VndMsPlayreadyMediaPyv,
        //[MediaTypeName("vnd.nokia.interleaved-multimedia")]
        //VndNokiaInterleavedMultimedia,
        //[MediaTypeName("vnd.nokia.mp4vr")]
        //VndNokiaMp4vr,
        //[MediaTypeName("vnd.nokia.videovoip")]
        //VndNokiaVideovoip,
        //[MediaTypeName("vnd.objectvideo")]
        //VndObjectvideo,
        //[MediaTypeName("vnd.planar")]
        //VndPlanar,
        //[MediaTypeName("vnd.radgamettools.bink")]
        //VndRadgamettoolsBink,
        //[MediaTypeName("vnd.radgamettools.smacker")]
        //VndRadgamettoolsSmacker,
        //[MediaTypeName("vnd.sealed.mpeg1")]
        //VndSealedMpeg1,
        //[MediaTypeName("vnd.sealed.mpeg4")]
        //VndSealedMpeg4,
        //[MediaTypeName("vnd.sealed.swf")]
        //VndSealedSwf,
        //[MediaTypeName("vnd.sealedmedia.softseal.mov")]
        //VndSealedmediaSoftsealMov,
        //[MediaTypeName("vnd.uvvu.mp4")]
        //VndUvvuMp4,
        //[MediaTypeName("vnd.youtube.yt")]
        //VndYoutubeYt,
        //[MediaTypeName("vnd.vivo")]
        //VndVivo,
        //[MediaTypeName("VP8")]
        //VP8,
        //[MediaTypeName("VP9")]
        //VP9,
    }
}
